-- Preenche a tabela municipios (MT) quando estiver vazia, para o app conseguir vincular cidades
-- sem rodar manualmente o seed (SECURITY DEFINER; só executa se COUNT = 0).

CREATE OR REPLACE FUNCTION public.seed_municipios_mt_if_empty()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF (SELECT COUNT(*)::int FROM municipios) > 0 THEN
    RETURN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM polos_regioes WHERE nome = 'Sinop' LIMIT 1) THEN
    RAISE EXCEPTION 'polos_regioes não encontrado. Aplique a migration de polos (polos_regioes).';
  END IF;

  INSERT INTO municipios (nome, nome_normalizado, polo_id, sub_regiao_cuiaba)
  SELECT DISTINCT ON (v.nome_normalizado) v.nome, v.nome_normalizado, p.id, NULL
  FROM (
    VALUES
      ('Acorizal', 'acorizal'),
      ('Agua Boa', 'agua boa'),
      ('Alta Floresta', 'alta floresta'),
      ('Alto Araguaia', 'alto araguaia'),
      ('Alto Boa Vista', 'alto boa vista'),
      ('Alto Garças', 'alto garcas'),
      ('Alto Paraguai', 'alto paraguai'),
      ('Alto Taquari', 'alto taquari'),
      ('Apiacas', 'apiacas'),
      ('Araguaiana', 'araguaiana'),
      ('Araguanta', 'araguanta'),
      ('Araputanga', 'araputanga'),
      ('Arenapolis', 'arenapolis'),
      ('Aripuana', 'aripuana'),
      ('Barao De Melgaco', 'barao de melgaco'),
      ('Barra Do Bugres', 'barra do bugres'),
      ('Barra Do Garcas', 'barra do garcas'),
      ('Bom Jesus Do Araguaia', 'bom jesus do araguaia'),
      ('Brasnorte', 'brasnorte'),
      ('Caceres', 'caceres'),
      ('Campinapolis', 'campinapolis'),
      ('Campo Novo Do Parecis', 'campo novo do parecis'),
      ('Campo Verde', 'campo verde'),
      ('Campos De Julio', 'campos de julio'),
      ('Canabrava Do Norte', 'canabrava do norte'),
      ('Canarana', 'canarana'),
      ('Carlinda', 'carlinda'),
      ('Castanheira', 'castanheira'),
      ('Chapada Dos Guimaraes', 'chapada dos guimaraes'),
      ('Claudia', 'claudia'),
      ('Cocalinho', 'cocalinho'),
      ('Colider', 'colider'),
      ('Colniza', 'colniza'),
      ('Comodoro', 'comodoro'),
      ('Confresa', 'confresa'),
      ('Cotriguacu', 'cotriguacu'),
      ('Cuiaba', 'cuiaba'),
      ('Curvelandia', 'curvelandia'),
      ('Denise', 'denise'),
      ('Diamantino', 'diamantino'),
      ('Dom Aquino', 'dom aquino'),
      ('Feliz Natal', 'feliz natal'),
      ('Gaucha Do Norte', 'gaucha do norte'),
      ('General Carneiro', 'general carneiro'),
      ('Guaranta Do Norte', 'guaranta do norte'),
      ('Guiratinga', 'guiratinga'),
      ('Indiavai', 'indiavai'),
      ('Ipiranga Do Norte', 'ipiranga do norte'),
      ('Itanhangá', 'itanhanga'),
      ('Itauba', 'itauba'),
      ('Itiquira', 'itiquira'),
      ('Jaciara', 'jaciara'),
      ('Jangada', 'jangada'),
      ('Jauru', 'jauru'),
      ('Juara', 'juara'),
      ('Juina', 'juina'),
      ('Juruena', 'juruena'),
      ('Juscimeira', 'juscimeira'),
      ('Lucas Do Rio Verde', 'lucas do rio verde'),
      ('Luciara', 'luciara'),
      ('Marcelandia', 'marcelandia'),
      ('Matupa', 'matupa'),
      ('Nobres', 'nobres'),
      ('Nortelandia', 'nortelandia'),
      ('Nossa Senhora Do Livramento', 'nossa senhora do livramento'),
      ('Nova Bandeirantes', 'nova bandeirantes'),
      ('Nova Brasilandia', 'nova brasilandia'),
      ('Nova Canaa Do Norte', 'nova canaa do norte'),
      ('Nova Guarita', 'nova guarita'),
      ('Nova Lacerda', 'nova lacerda'),
      ('Nova Marilandia', 'nova marilandia'),
      ('Nova Maringa', 'nova maringa'),
      ('Nova Monte Verde', 'nova monte verde'),
      ('Nova Mutum', 'nova mutum'),
      ('Nova Nazare', 'nova nazare'),
      ('Nova Olimpia', 'nova olimpia'),
      ('Nova Santa Helena', 'nova santa helena'),
      ('Nova Ubirata', 'nova ubirata'),
      ('Nova Xavantina', 'nova xavantina'),
      ('Novo Horizonte Do Norte', 'novo horizonte do norte'),
      ('Novo Mundo', 'novo mundo'),
      ('Novo Santo Antonio', 'novo santo antonio'),
      ('Novo Sao Joaquim', 'novo sao joaquim'),
      ('Oeste', 'oeste'),
      ('Paranaita', 'paranaita'),
      ('Paranatinga', 'paranatinga'),
      ('Pedra Preta', 'pedra preta'),
      ('Peixoto De Azevedo', 'peixoto de azevedo'),
      ('Planalto Da Serra', 'planalto da serra'),
      ('Pocone', 'pocone'),
      ('Pontes E Lacerda', 'pontes e lacerda'),
      ('Porto Alegre Do Norte', 'porto alegre do norte'),
      ('Porto Dos Gauchos', 'porto dos gauchos'),
      ('Porto Esperidiao', 'porto esperidiao'),
      ('Porto Estrela', 'porto estrela'),
      ('Poxoreo', 'poxoreo'),
      ('Primavera Do Leste', 'primavera do leste'),
      ('Querencia', 'querencia'),
      ('Reserva Do Cabacal', 'reserva do cabacal'),
      ('Ribeirao Cascalheira', 'ribeirao cascalheira'),
      ('Ribeiraozinho', 'ribeiraozinho'),
      ('Rio Branco', 'rio branco'),
      ('Rondolandia', 'rondolandia'),
      ('Rondonopolis', 'rondonopolis'),
      ('Rosario Oeste', 'rosario oeste'),
      ('Salto Do Ceu', 'salto do ceu'),
      ('Santa Carmem', 'santa carmem'),
      ('Santa Cruz Do Xingu', 'santa cruz do xingu'),
      ('Santa Rita Do Trivelato', 'santa rita do trivelato'),
      ('Santa Terezinha', 'santa terezinha'),
      ('Santo Afonso', 'santo afonso'),
      ('Santo Antonio Do Leste', 'santo antonio do leste'),
      ('Santo Antonio Do Leverger', 'santo antonio do leverger'),
      ('Sao Felix Do Araguaia', 'sao felix do araguaia'),
      ('Sao Jose Do Povo', 'sao jose do povo'),
      ('Sao Jose Do Rio Claro', 'sao jose do rio claro'),
      ('Sao Jose Do Xingu', 'sao jose do xingu'),
      ('Sao Jose Dos Quatro Marcos', 'sao jose dos quatro marcos'),
      ('Sao Pedro Da Cipa', 'sao pedro da cipa'),
      ('Sapezal', 'sapezal'),
      ('Serra Nova Dourada', 'serra nova dourada'),
      ('Sinop', 'sinop'),
      ('Sorriso', 'sorriso'),
      ('Tabapora', 'tabapora'),
      ('Tangara Da Serra', 'tangara da serra'),
      ('Tapurah', 'tapurah'),
      ('Terra Nova Do Norte', 'terra nova do norte'),
      ('Tesouro', 'tesouro'),
      ('Torixoreu', 'torixoreu'),
      ('Uniao Do Sul', 'uniao do sul'),
      ('Vale De Sao Domingos', 'vale de sao domingos'),
      ('Varzea Grande', 'varzea grande'),
      ('Vera', 'vera'),
      ('Vila Rica', 'vila rica')
  ) AS v(nome, nome_normalizado)
  CROSS JOIN LATERAL (SELECT id FROM polos_regioes WHERE nome = 'Sinop' LIMIT 1) AS p(id)
  ORDER BY v.nome_normalizado, v.nome
  ON CONFLICT (nome_normalizado) DO NOTHING;
END;
$$;

REVOKE ALL ON FUNCTION public.seed_municipios_mt_if_empty() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.seed_municipios_mt_if_empty() TO authenticated;
