-- Reativa Row Level Security nas tabelas públicas do CampanhaMT.
-- Corrige o alerta de segurança «tabela de acesso público» / RLS desativado no Table Editor.
-- Idempotente: `ENABLE ROW LEVEL SECURITY` não duplica nada.
--
-- As políticas (CREATE POLICY) vêm das migrações anteriores. Se o projeto foi criado à mão
-- sem políticas, o app pode falhar até correr `supabase db push` completo desde o início.

ALTER TABLE IF EXISTS polos_regioes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS municipios ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS assessores ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS apoiadores ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS votantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS benfeitorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS metas_regionais ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS meta_estadual ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS reunioes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS concorrentes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mensagens ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS dados_tse ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS aniversariantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS reunioes_presenca ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS campanha_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS responsavel_regiao ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS votacao_secao ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mapa_regioes_custom ENABLE ROW LEVEL SECURITY;
